version: "3.5"
services:
    nginx:
      image: nginx:latest
      env_file:
        - .env
      ports:
        - "80:80"
      volumes:
        - .:/src
        - asset-volume:/home
        - ./config:/etc/nginx/conf.d
      deploy:
        restart_policy:
          max_attempts: 3
          condition: on-failure
        replicas: 4
        placement:
          constraints: [node.role == manager]
      networks: 
        - edms_main_network
      depends_on:
        - web
    web:
      env_file:
        - .env
      build: .
      image: edms_image:latest
      deploy:
        restart_policy:
          max_attempts: 4
          condition: on-failure
        replicas: 3
        placement:
          constraints: [node.role == manager]
      volumes:
        - asset-volume:/home
        - .:/src
      networks: 
        - edms_main_network
networks: 
  edms_main_network:
      driver: overlay
volumes:
    asset-volume:
    