version: "2"
services:
  nginx:
    image: nginx:latest
    env_file:
      - .env
    container_name: nginxedmsv2frontend
    ports:
      # - "8000:8000"
      - "5600:5600"
    volumes:
      - .:/src
      - ./config:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    env_file:
      - .env
    build: .
    container_name: ngedmsv2frontend
    volumes:
      - .:/src
    expose:
      - "5600"
